version: "3"

services:

  proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
    - "80:80"     # The HTTP port
    - "8080:8080" # The Web UI (enabled by --api)
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  whoami:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    labels:
    - traefik.frontend.rule=Host:test.${BASE_DOMAIN}
  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    command: revel run github.com/klim0v/golang-revel-realworld-starter-kit
    working_dir: /go
    labels:
    - traefik.backend=realworld
    - traefik.frontend.rule=Host:api.${BASE_DOMAIN}
    - traefik.docker.network=proxy
    - traefik.port.rule=9000
    expose:
    - 9000
    env_file:
    - .env
    volumes:
    - ./:/go/src/github.com/klim0v/golang-revel-realworld-starter-kit
    links:
    - db
    depends_on:
    - db

  adminer:
    image: adminer:4.6.3-standalone
    labels:
    - traefik.backend=adminer
    - traefik.frontend.rule=Host:db-admin.${BASE_DOMAIN}
    - traefik.docker.network=proxy
    - traefik.port=8080
    depends_on:
    - db

  db:
    image: mysql:5.7
    volumes:
    - ./docker/runtime/mysql:/var/lib/mysql
    - ./docker/db/dump/newdb.sql:/docker-entrypoint-initdb.d/newdb.sql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 123123
    labels:
    - traefik.enable=false
